server.port: 8081
server.error.include-message: always

logging:
  level:
    root: INFO

spring:
  application:
    name: Ventas-Application
  data:
    mongodb:
      uri: mongodb+srv://admin:admin123@cluster0.0lmgwdx.mongodb.net/
      database: Ventas
      auto-index-creation: true